/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.AbstractJavaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class JavaRuntimeModule extends AbstractJavaRuntimeModule {
}
