/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.validation;

import org.xtext.example.mydsl.validation.AbstractJavaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class JavaValidator extends AbstractJavaValidator {
}
