/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.compiladores20171.javaToAssembly.ui.internal.JavaToAssemblyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JavaToAssemblyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JavaToAssemblyActivator.getInstance().getInjector(JavaToAssemblyActivator.ORG_XTEXT_EXAMPLE_MYDSL_JAVA);
	}
	
}
