/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.mydsl.JavaRuntimeModule
import org.xtext.example.mydsl.JavaStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class JavaIdeSetup extends JavaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new JavaRuntimeModule, new JavaIdeModule))
	}
	
}
