/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.JavaRuntimeModule;
import org.xtext.example.mydsl.JavaStandaloneSetup;
import org.xtext.example.mydsl.ide.JavaIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class JavaIdeSetup extends JavaStandaloneSetup {
  @Override
  public Injector createInjector() {
    JavaRuntimeModule _javaRuntimeModule = new JavaRuntimeModule();
    JavaIdeModule _javaIdeModule = new JavaIdeModule();
    return Guice.createInjector(Modules2.mixin(_javaRuntimeModule, _javaIdeModule));
  }
}
