/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractJavaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class JavaIdeModule extends AbstractJavaIdeModule {
}
