/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.compiladores20171.javaToAssembly.ui.internal.JavaToAssemblyActivator;

public class JavaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JavaToAssemblyActivator.getInstance().getInjector("org.xtext.example.mydsl.Java");
	}

}
